definitions:
  etre.Entity:
    additionalProperties: true
    type: object
  etre.Error:
    properties:
      entityId:
        description: entity ID that caused error, if any
        type: string
      httpStatus:
        description: HTTP status code
        type: integer
      message:
        description: human-readable and loggable error message
        type: string
      type:
        description: error slug (e.g. db-error, missing-param, etc.)
        type: string
    type: object
info:
  contact: {}
paths:
  /entities/:type:
    get:
      description: |-
        Query entities of a type specified by the :type endpoint.
        Returns a set of entities matching the labels in the `query` query parameter.
        All labels of each entity are returned, unless specific labels are specified in the `labels` query parameter.
        The result set is reduced to distinct values if the request includes the `distinct` query parameter (requires `lables` name a single label).
        If the query is longer than 2000 characters, use the POST /query endpoint (to be implemented).
      operationId: getEntitiesHandler
      parameters:
      - description: Entity type
        in: path
        name: type
        required: true
        type: string
      - description: Selector
        in: query
        name: query
        required: true
        type: string
      - description: Comma-separated list of labels to return
        in: query
        name: labels
        type: string
      - description: Reduce results to one per distinct value
        in: query
        name: distinct
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/etre.Entity'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/etre.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/etre.Error'
      summary: Query a set of entities
swagger: "2.0"
